// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdnpclukentpzptzfndr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbnBjbHVrZW50cHpwdHpmbmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTQyNzAsImV4cCI6MjA2Nzc5MDI3MH0.j0bjWgh92heJIBUvcRTZnMkX6VnPk8fq3UnlkvuXk7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});